name: telegram_bot
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  bloc_test: ^8.5.0
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter

  flutter_bloc: ^7.3.3
  freezed: ^0.15.1+1
  http: ^0.13.4
  logger: ^1.1.0
  teledart: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4

#
flutter:
  uses-material-design: true


